### ISSUE TITLE
Finding ID relveant to my crushmap

### ISSUE THREAD

**Issue by DylanGraham** [maricaantonacci/ceph-tutorial#1]
**Enable Cache Tier**
`Note: the ids of the added entities may be different`
Hi, can you explain this line of your document?
How do I determine the ID of my SSD root object in the crushmap?
Thank you

**Comment by maricaantonacci** [comment]
Hi,
when you download and decompile your crush map you get a text file containing a list of entities (buckets) that are identified by a unique id. Typically the id is a negative integer. When you want to modify the crush map adding a new bucket you have to add a section with the following syntax:

<pre>
[bucket-type] [bucket-name] {
        id [a unique negative numeric ID]
        weight [the relative capacity/capability of the item(s)]
        alg [the bucket type: uniform | list | tree | straw ]
        hash [the hash type: 0 by default]
        item [item-name] weight [weight]
}
</pre>

where `id` must be a negative integer different from all the others already present in the crush map you are modifying.
Hope this is clear. For futher information you can look at the ceph documentation about the crush map: http://docs.ceph.com/docs/jewel/rados/operations/crush-map/
